package com.sam_mc.travelyourearth.item;

import com.google.common.collect.Maps;
import com.sam_mc.travelyourearth.TravelYourEarth;
import com.sam_mc.travelyourearth.sound.ModSounds;
import com.sam_mc.travelyourearth.tags.ModTags;
import net.minecraft.core.Registry;
import net.minecraft.resources.Identifier;
import net.minecraft.resources.ResourceKey;
import net.minecraft.world.item.equipment.ArmorMaterial;
import net.minecraft.world.item.equipment.ArmorType;
import net.minecraft.world.item.equipment.EquipmentAsset;

import java.util.Map;

/** Armor materials of the mod (ruby, between iron and diamond). */
public class ModArmorMaterials {

    // =========================================================================
    // Equipment asset keys
    // =========================================================================

    /** Registry of equipment assets (minecraft:equipment_asset). */
    public static final ResourceKey<? extends Registry<EquipmentAsset>> ROOTID = ResourceKey.createRegistryKey(Identifier.withDefaultNamespace("equipment_asset"));

    /** Ruby equipment asset -> assets/travelyourearth/equipment/ruby.json (generated by ModEquipmentAssetProvider). */
    public static final ResourceKey<EquipmentAsset> RUBY_KEY = ResourceKey.create(ROOTID, Identifier.fromNamespaceAndPath(TravelYourEarth.MODID, "ruby"));

    // =========================================================================
    // Materials
    // =========================================================================

    /**
     * Ruby armor (iron: durability 15, diamond: 33).
     *   durability multiplier 24 | defense: boots 2, leggings 6, chestplate 7, helmet 3, body 8
     *   enchantability 18 | equip sound: ruby clink | toughness 1 | knockback resistance 0
     *   repaired with #travelyourearth:ruby_repairable
     */
    public static final ArmorMaterial RUBY_ARMOR_MATERIAL = new ArmorMaterial(24,
            makeDefense(2, 6, 7, 3, 8), 18, ModSounds.ARMOR_EQUIP_RUBY,
            1f, 0f, ModTags.Items.RUBY_REPAIRABLE, RUBY_KEY);

    // =========================================================================
    // Helpers
    // =========================================================================

    /** Defense points per armor piece ("body" = horse / nautilus armor). */
    private static Map<ArmorType, Integer> makeDefense(int boots, int legs, int chest, int helm, int body) {
        return Maps.newEnumMap(
                Map.of(ArmorType.BOOTS, boots, ArmorType.LEGGINGS, legs, ArmorType.CHESTPLATE, chest, ArmorType.HELMET, helm, ArmorType.BODY, body)
        );
    }
}