package com.sam_mc.travelyourearth.event;

import com.sam_mc.travelyourearth.TravelYourEarth;
import com.sam_mc.travelyourearth.item.ModItems;
import net.minecraft.advancements.AdvancementHolder;
import net.minecraft.core.BlockPos;
import net.minecraft.core.particles.ParticleTypes;
import net.minecraft.resources.Identifier;
import net.minecraft.server.level.ServerLevel;
import net.minecraft.server.level.ServerPlayer;
import net.minecraft.sounds.SoundEvents;
import net.minecraft.tags.BlockTags;
import net.minecraft.world.entity.EquipmentSlot;
import net.minecraft.world.entity.LivingEntity;
import net.minecraft.world.item.ItemStack;
import net.minecraft.world.level.block.Blocks;
import net.minecraft.world.level.block.state.BlockState;
import net.neoforged.bus.api.SubscribeEvent;
import net.neoforged.fml.common.EventBusSubscriber;
import net.neoforged.neoforge.event.tick.EntityTickEvent;

import java.util.Map;
import java.util.WeakHashMap;

/**
 * Ruby armor: puts out the fire of whoever wears it as soon as they leave the fire/lava.
 * It works with any piece (helmet, chestplate, leggings, boots, horse armor or nautilus armor).
 * After putting it out, there's a 2 second cooldown before it can put it out again.
 *
 * If it's a player, it grants the "Fireproof" advancement.
 */
@EventBusSubscriber(modid = TravelYourEarth.MODID)
public class RubyArmorFireHandler {

    // =========================================================================
    // Constants
    // =========================================================================

    private static final int COOLDOWN_TICKS = 2 * 20; // 2 seconds

    /**
     * "Fireproof" advancement (generated by ModAdvancementProvider). There are two versions and
     * only ONE is loaded, depending on the "modAdvancementTab" config option:
     */
    public static final Identifier FIREPROOF_ADVANCEMENT =                 // Adventure tab (OFF)
            Identifier.fromNamespaceAndPath(TravelYourEarth.MODID, "adventure/fireproof");
    public static final Identifier FIREPROOF_ADVANCEMENT_MOD_TAB =         // mod tab (ON)
            Identifier.fromNamespaceAndPath(TravelYourEarth.MODID, "ruby/fireproof");
    /** Name of the criterion inside the advancement. */
    public static final String FIREPROOF_CRITERION = "ruby_armor_extinguished";

    /**
     * Entity -> game tick from which it can be put out again.
     * WeakHashMap: when the entity dies or unloads, Java removes its entry by itself
     * (with a normal HashMap by UUID, the map grew forever).
     */
    private static final Map<LivingEntity, Long> NEXT_EXTINGUISH_TICK = new WeakHashMap<>();

    // =========================================================================
    // Event
    // =========================================================================

    @SubscribeEvent
    public static void onEntityTick(EntityTickEvent.Pre event) {
        if (!(event.getEntity() instanceof LivingEntity entity)) return;
        if (!(entity.level() instanceof ServerLevel level)) return;

        // Cheapest checks first: this runs for EVERY entity on EVERY tick
        if (!entity.isOnFire()) return;
        if (!hasAnyRubyArmorEquipped(entity)) return;

        // Cooldown: we compare with the world time (instead of subtracting 1 every tick)
        long now = level.getGameTime();
        Long nextAllowed = NEXT_EXTINGUISH_TICK.get(entity);
        if (nextAllowed != null && now < nextAllowed) return;

        // Intentional: undead mobs with ruby in the sun also get put out every 2 s,
        // so they keep burning and die, but more slowly.

        // If it's still inside fire or lava, it isn't put out (it would catch fire again instantly)
        if (entity.isInLava() || isTouchingFireOrLava(entity)) return;

        // 1. Put out the fire
        entity.clearFire();

        // 2. Sound and smoke
        level.playSound(
                null,
                entity.getX(), entity.getY(), entity.getZ(),
                SoundEvents.FIRE_EXTINGUISH,
                entity.getSoundSource(), // player -> PLAYERS, zombie -> HOSTILE, horse -> NEUTRAL...
                1.0F,
                1.0F
        );
        level.sendParticles(
                ParticleTypes.WHITE_SMOKE,
                entity.getX(), entity.getY() + 1.0, entity.getZ(),
                25,
                0.3, 0.4, 0.3,
                0.05
        );

        // 3. 2 second cooldown
        NEXT_EXTINGUISH_TICK.put(entity, now + COOLDOWN_TICKS);

        // 4. "Fireproof" advancement (if it's already earned, award() does nothing).
        //    We try both versions: the one that isn't loaded returns null and is skipped.
        if (entity instanceof ServerPlayer player) {
            for (Identifier id : new Identifier[]{FIREPROOF_ADVANCEMENT, FIREPROOF_ADVANCEMENT_MOD_TAB}) {
                AdvancementHolder advancement = level.getServer().getAdvancements().get(id);
                if (advancement != null) {
                    player.getAdvancements().award(advancement, FIREPROOF_CRITERION);
                }
            }
        }
    }

    // =========================================================================
    // Helpers
    // =========================================================================

    /** Is any block inside its collision box fire, soul fire or lava? */
    private static boolean isTouchingFireOrLava(LivingEntity entity) {
        return BlockPos.betweenClosedStream(entity.getBoundingBox())
                .anyMatch(pos -> {
                    BlockState state = entity.level().getBlockState(pos);
                    return state.is(BlockTags.FIRE) || state.is(Blocks.LAVA); // FIRE = fire + soul fire
                });
    }

    private static boolean hasAnyRubyArmorEquipped(LivingEntity entity) {
        for (EquipmentSlot slot : EquipmentSlot.values()) {
            if (slot.getType() == EquipmentSlot.Type.HUMANOID_ARMOR) {
                ItemStack stack = entity.getItemBySlot(slot);
                if (stack.is(ModItems.RUBY_HELMET.get())
                        || stack.is(ModItems.RUBY_CHESTPLATE.get())
                        || stack.is(ModItems.RUBY_LEGGINGS.get())
                        || stack.is(ModItems.RUBY_BOOTS.get())) {
                    return true;
                }
            }
        }

        ItemStack bodyStack = entity.getItemBySlot(EquipmentSlot.BODY);
        return bodyStack.is(ModItems.RUBY_HORSE_ARMOR.get())
                || bodyStack.is(ModItems.RUBY_NAUTILUS_ARMOR.get());
    }
}